### ISSUE TITLE
Implementation status

### ISSUE THREAD

**Issue by inuex35** [inuex35/gsplat#1]
Working on spherical_render branch

### Todo

- [x] Load Opensfm data for spherical camera
- [x] Render forward - Need to check pixels are in the right position
- [x] Render forward - Need to check if jacobian is okay
- [x] Render backward - Need to check mathematical correctness for backward

Current status
Forward pass is not good
![Frame_00115_FinalColor](https://github.com/user-attachments/assets/9b3f2120-95da-4a1c-a78b-9706b90dc630)

### Sample dataset

https://dtbn.jp/6eEZeo8e
(The url will expire in a week)

image
![363364054-58ee52a3-4200-4397-bd81-b876470dfaf6](https://github.com/user-attachments/assets/718a4e2e-ad21-4d37-b2f2-d349ba942c02)

reconstruction
![363273991-74f99747-e588-484f-a6d6-feffef6627d9 (1)](https://github.com/user-attachments/assets/5b377cc9-37fa-4cfd-a678-5cada64665b9)

**Comment by inuex35** [comment]
Forward pass is look okay

![Frame_00105_FinalColor](https://github.com/user-attachments/assets/8baa0ab8-0762-470c-af59-e1ce89a94f91)

![image](https://github.com/user-attachments/assets/07ef7d46-a0e8-436c-a638-d1d6b3a98e01)

Iterations 7000
![image](https://github.com/user-attachments/assets/0f3c5c62-27f1-46e6-b3da-6d274e1982e9)

Iterations 30000
![image](https://github.com/user-attachments/assets/ec620ddc-1a7d-4d71-8105-d4506205ca88)

rendering result is not good and need to check jacobian and backward

![image](https://github.com/user-attachments/assets/1788795f-c04d-427b-ac3a-1dd7cefa9109)

**Comment by inuex35** [comment]
Worked! I dont know why it's upside down.

![image](https://github.com/user-attachments/assets/c7281ed9-3b60-4f55-a037-d5ecc1558164)


https://github.com/user-attachments/assets/d9eff32d-0c4b-4c50-a2ed-080883eabe5e



Problem was the original dataset. It does not happen in another dataset.

![image](https://github.com/user-attachments/assets/aa3d2778-e548-48c1-ba24-30955e0aa30f)

**Comment by inuex35** [comment]
Real data is not as good as simulated data, but looks working well.

https://github.com/user-attachments/assets/192cc732-d8e6-4c3e-a9eb-45e89b315388

Rendering perspective from spherical model is okay but smoky because of large floaters under ground.

![image](https://github.com/user-attachments/assets/4d76933e-47b5-4942-a9d8-5438b818f51d)

**Comment by weixiabing** [comment]
Excellent contribution, I tested the code on the OmniBlender dataset and found that the default strategy has a sharp rise in loos after the 3000th step and seems to reset the opacity every 100 steps after that, resulting in a poor encounter, whereas with the mcmc strategy my psnr was 5db higher than the results on the omnigs paper!
